import { AppProviders } from './Components/app-providers'
import Navigation from './Components/navigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Student Manager By QunnTr',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
        <Navigation className="bg-gray-500"></Navigation>
        {children}</AppProviders></body>
    </html>
  )
}
